### PR TITLE
Remove styled-components as a dependency and make it a peer dependency.

### PR DESCRIPTION
**Pull request by garretttaco**
This removes the possibility of issues like https://github.com/styled-components/styled-components/issues/1076 and https://github.com/styled-components/styled-components/issues/1032 from arising. 
This is also requested in https://github.com/jxnblk/grid-styled/issues/88.

I did notice your comment https://github.com/jxnblk/grid-styled/pull/63#issuecomment-362871558
but with styled-components not allowing multiple instances of itself on the page, it is more problematic for this library to have it as a dependency vs a peer dependency. If I am using grid-styled, chances are high that I am already using styled-components in my app and will already be installing it.

### CODE REVIEW

**Comment by jxnblk** [comment]
1. The versioning on this library should be loose enough that it won't install a separate styled-components dependency in the `node_modules/grid-styled/node_modules/` folder, and I'm slightly concerned that people have their build set up in a not-so-great way. I am unable to reproduce this on my end.
2. I know the styled-components docs recommend using peerDependencies for libraries, but this shouldn't be necessary
3. This is a *breaking change* which means I'd have to bump the major version again

**Comment by garretttaco** [comment]
It looks like you just updated the peer dependency criteria for styled-components 20 days ago. I did not see that. We have the previous version that specifies `v3.1.5`. We are using styled-components v2 so we were getting two different versions of styled-components. I am going to try upgrading first to see if that solves the issue. See the screen show below for context.
screen shot 2018-02-23 at 2 49 01 pm


Would it be possible to consider making this change for your next major release? The use case of people using grid-styled and not styled-components cannot be more than not. Based on the previous PRs and opened issues, I am clearly not the first person this has affected.

**Comment by jxnblk** [comment]
Thanks for checking on the latest version. I'll certainly consider it again, but I'm fairly certain, despite what the numbers may be, that there will be issues created for *not* having it in dependencies. As a library author, this is a tough thing to manage since there are many different ways to set up app bundling, but generally I prefer to side on how things *should* work with npm.

That said, I would be more than happy to add more documentation for troubleshooting issues that arise from duplicative dependencies, so please let me know how it goes on your end

**Comment by aewing** [comment]
I can see why making a change here is a difficult choice to make. Damned if you do... My preference as the potentially affected developer would be to deal with the requirement to install the peer dependency. This is something that is easily addressed -- and I think most would be able to discern from the error messages provided what they'd need to do to solve the problem. Debugging version conflicts and the lack of errors provided with them is a time consuming endeavor.

**Comment by jpdesigndev** [comment]
I am also being affected by this issue, and I'm not sure where to start. If I keep a dep on styled components pegged at `^2.1.2`, my app works in dev, but not in production. If I upgrade my styled components dependency to `^3.2.0`, my app breaks in dev and production builds. Any clues?

**Comment by jpdesigndev** [comment]
I've found that if I include the exact version that is currently being used by grid-styled `3.1.6`, everything works ok. Otherwise, problems are likely to occur.

**Comment by jpdesigndev** [comment]
@duro Perhaps you could try to clean your yarn or npm cache. I'm not certain which series of events allowed me to lock in on `3.1.6`. This, of course, is scary to me :)

I'll see if I can gather some more details about what should work.

**Comment by duro** [comment]
@jpdesigndev @jxnblk I was actually able to get this to install only one version of styled-components by setting my deps to `"styled-components": "^3.0.0",`

This installed one version of styled-components 3.2.0.

Both dev and prod builds are working. I did have to do a bunch of prop renaming to move over to the new flex prop names, but everything is working now.

**Comment by DJTB** [comment]
Ran into the same issue + solution as @duro

**Comment by chrishurlburt** [comment]
I also would like to throw my support into the mix for this PR as it's been a blocker for me in a project. For what it's worth, almost all the styled-component grid libs here have styled-components as a peerDependency: [https://github.com/styled-components/awesome-styled-components#grid-systems](https://github.com/styled-components/awesome-styled-components#grid-systems)

**Comment by kytwb** [comment]
@chrishurlburt brought up a good point. I'd be for merging this PR as well.

**Comment by DJTB** [comment]
If I upgrade `styled-components` via `yarn upgrade-interactive` my `yarn.lock` changes from:  
```
styled-components@3.2.2, "styled-components@>=2.0 || >=3.0", styled-components@>=3.0.0:
  version "3.2.2"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-3.2.2.tgz#3a3a49e0009a212d1fee173e3a7719a489e11299"
  dependencies:
    buffer "^5.0.3"
    css-to-react-native "^2.0.3"
    fbjs "^0.8.9"
    hoist-non-react-statics "^1.2.0"
    is-plain-object "^2.0.1"
    opencollective "^1.0.3"
    prop-types "^15.5.4"
    stylis "^3.5.0"
    stylis-rule-sheet "^0.0.10"
    supports-color "^3.2.3"
```
to:  

```
styled-components@3.2.3:
  version "3.2.3"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-3.2.3.tgz#50f71207320eeb1ef539dec4637f21f5e3c936b4"
  dependencies:
    buffer "^5.0.3"
    css-to-react-native "^2.0.3"
    fbjs "^0.8.9"
    hoist-non-react-statics "^1.2.0"
    is-plain-object "^2.0.1"
    opencollective "^1.0.3"
    prop-types "^15.5.4"
    stylis "^3.5.0"
    stylis-rule-sheet "^0.0.10"
    supports-color "^3.2.3"

"styled-components@>=2.0 || >=3.0", styled-components@>=3.0.0:
  version "3.2.2"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-3.2.2.tgz#3a3a49e0009a212d1fee173e3a7719a489e11299"
  dependencies:
    buffer "^5.0.3"
    css-to-react-native "^2.0.3"
    fbjs "^0.8.9"
    hoist-non-react-statics "^1.2.0"
    is-plain-object "^2.0.1"
    opencollective "^1.0.3"
    prop-types "^15.5.4"
    stylis "^3.5.0"
    stylis-rule-sheet "^0.0.10"
    supports-color "^3.2.3"
```

Though one **can** work around this by changing the version to `>3.2.3` in `package.json`, deleting `node_modules` and `yarn.lock`, and reinstalling...
* It's a pain to remember to do this
* Have to clear caching on CI as well and rebuild from scratch
* You lose the benefit of having an **exact** version specified -> potential regressions due to unwanted upgrades, different versions between machines


Note: I have styled-system as well as rebass installed if that makes a difference*

**Comment by xDae** [comment]
Im not sure if its related to this, but Im having this problem:

screen shot 2018-04-03 at 16 56 28

**Comment by lcsrinaldi** [comment]
Still suffering from this problem :(

**Comment by garretttaco** [comment]
@lcsrinaldi Unfortunately, for me to effectively solve this issue, I had to use a forked version of grid-styled where styled-components is a peer-dependency. Nothing else seemed to work. If this PR is merged, I will be able to start using this again. I hope it is eventually!

**Comment by jablonnc** [comment]
@jxnblk Do we have a verdict on this?  If you plan on merging this sometime soon I plan on waiting, otherwise I will fork as @garretttaco has done.

**Comment by joseph-galindo** [comment]
+1 to the above sentiment, planning to fork without this PR.

**Comment by morganney** [comment]
Library authors need to use styled-components as a peer dependency. Nuff said: https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

**Comment by nmrshll** [comment]
Following @jpdesigndev 's answer I was able to fix the problem by changing the version of `styled-components` in my project's package.json and setting it to the same value as the `styled-components` used in `grid-styled`. (currently `"styled-components": "3.2.5"`)

A fix (using peer dependencies) in the next major version would be nice though, as this would break again if I chose to use another package that forces me to use its version of `styled-components`

**Comment by jxnblk** [comment]
@garretttaco sorry for the delay on this. After considering this change, I plan on merging this in and publishing a new major version – thanks again for helping out here!

**Pull request merged**
