### PR TITLE
Replace φ special character

### PR DESCRIPTION
**Pull request by lachlanjc**
According to #52 the special character is problematic, so I’ve replaced it here.

### CODE REVIEW

**Comment by acz13** [comment]
probably would make more sense using `phi` or `gr`

**Comment by adamellsworth** [comment]
Same issue:
https://github.com/jxnblk/grid-styled/pull/53

**Comment by jxnblk** [comment]
Thanks for this!

1. This would mean a breaking change
2. Most apps should probably be setting `<meta charset='utf-8'>` IMO

That said, using a unicode character is completely unnecessary, so I'll likely keep this PR open until preparing for the next major version.

**Comment by jxnblk** [comment]
Ended up just removing the Golden component altogether in v3, but thanks again for the PR!

**Pull request closed without merging**
